version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - importShadow
    gocyclo:
      min-complexity: 10
    gosec:
      excludes:
        - G104
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    staticcheck:
      checks:
        - all
        - -ST1000
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - dupl
        path: .*\/handler\/.*\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/atsumarukun/holos-storage-api
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
