run:
  timeout: 5m

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
    disable:
      - "fieldalignment"
      - "shadow"
  staticcheck:
    checks: ["all"]
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 10
  goimports:
    local-prefixes: github.com/atsumarukun/holos-account-api
  dupl:
    threshold: 100
  gosec:
    excludes:
      - G104

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - gocritic
    - goconst
    - gocyclo
    - goimports
    - dupl
    - gosec
    - unused
    - copyloopvar
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - dupl
  exclude-use-default: false
