// Code generated by MockGen. DO NOT EDIT.
// Source: body.go
//
// Generated by this command:
//
//	mockgen -source=body.go -package=service -destination=../../../../../test/mock/domain/service/body.go
//

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	entity "github.com/atsumarukun/holos-storage-api/internal/app/api/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockBodyService is a mock of BodyService interface.
type MockBodyService struct {
	ctrl     *gomock.Controller
	recorder *MockBodyServiceMockRecorder
	isgomock struct{}
}

// MockBodyServiceMockRecorder is the mock recorder for MockBodyService.
type MockBodyServiceMockRecorder struct {
	mock *MockBodyService
}

// NewMockBodyService creates a new mock instance.
func NewMockBodyService(ctrl *gomock.Controller) *MockBodyService {
	mock := &MockBodyService{ctrl: ctrl}
	mock.recorder = &MockBodyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBodyService) EXPECT() *MockBodyServiceMockRecorder {
	return m.recorder
}

// BuildPath mocks base method.
func (m *MockBodyService) BuildPath(arg0 *entity.Volume, arg1 *entity.Entry) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildPath", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildPath indicates an expected call of BuildPath.
func (mr *MockBodyServiceMockRecorder) BuildPath(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildPath", reflect.TypeOf((*MockBodyService)(nil).BuildPath), arg0, arg1)
}
