// Code generated by MockGen. DO NOT EDIT.
// Source: entry.go
//
// Generated by this command:
//
//	mockgen -source=entry.go -package=service -destination=../../../../../test/mock/domain/service/entry.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	io "io"
	reflect "reflect"

	entity "github.com/atsumarukun/holos-storage-api/internal/app/api/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockEntryService is a mock of EntryService interface.
type MockEntryService struct {
	ctrl     *gomock.Controller
	recorder *MockEntryServiceMockRecorder
	isgomock struct{}
}

// MockEntryServiceMockRecorder is the mock recorder for MockEntryService.
type MockEntryServiceMockRecorder struct {
	mock *MockEntryService
}

// NewMockEntryService creates a new mock instance.
func NewMockEntryService(ctrl *gomock.Controller) *MockEntryService {
	mock := &MockEntryService{ctrl: ctrl}
	mock.recorder = &MockEntryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryService) EXPECT() *MockEntryServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEntryService) Create(arg0 context.Context, arg1 *entity.Volume, arg2 *entity.Entry, arg3 io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEntryServiceMockRecorder) Create(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEntryService)(nil).Create), arg0, arg1, arg2, arg3)
}

// Exists mocks base method.
func (m *MockEntryService) Exists(arg0 context.Context, arg1 *entity.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockEntryServiceMockRecorder) Exists(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockEntryService)(nil).Exists), arg0, arg1)
}
