name: Code Test

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Set up go
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Run lint
        uses: golangci/golangci-lint-action@v8.0.0

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Set up go
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Run test
        run: go test ./...
