name: Deploy API

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Build and push
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: build/package/Dockerfile.deploy
          push: true
          platform: linux/amd64
          provenance: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/holos-account-api:latest
            ghcr.io/${{ github.repository_owner }}/holos-account-api:${{ github.ref_name }}

  release:
    runs-on: ubuntu-latest
    needs: deploy

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
