name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-swagger-ui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install swagger cli
        run: npm install -g swagger-cli

      - name: Generate swagger ui
        uses: Legion2/swagger-ui-action@v1.3.0
        with:
          output: swagger-ui
          spec-file: ./api/openapi.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload documents
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: swagger-ui

  deploy-swagger-ui:
    runs-on: ubuntu-latest
    needs: build-swagger-ui

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5

  deploy-api:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Build and push
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: build/package/Dockerfile.deploy
          push: true
          platform: linux/amd64
          provenance: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/holos-storage-api:latest
            ghcr.io/${{ github.repository_owner }}/holos-storage-api:${{ github.ref_name }}

  release:
    runs-on: ubuntu-latest
    needs: [deploy-swagger-ui, deploy-api]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
